In [64]:
# load the libraries 
import numpy as np
import pandas as pd
import h5py
import math
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from scipy.ndimage.filters import gaussian_filter
from sklearn.model_selection import train_test_split
from numpy import savetxt

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.utils import np_utils
from keras.datasets import mnist

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import MaxPooling2D
from keras import backend as K
from keras.models import Model

import math
import numpy as np
import h5py
import matplotlib.pyplot as plt
import scipy
from PIL import Image
from scipy import ndimage
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.utils import np_utils
from keras.datasets import mnist

import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import MaxPooling2D
from keras import backend as K
from keras.models import Model

from sklearn.model_selection import train_test_split
import pickle

#from keras.layers import Input, Dense

import numpy as np

from keras.layers import InputLayer

from keras.layers import Conv2D

from keras.layers import Input, Dense


In [2]:
# this is the folder where you put the files you need for the data, on my hard drive it looks like this :
folder='C:/CS230/dendritic'

In [3]:
genes= pd.read_table(folder+"/genes.txt",index_col=1,header=None,names=['gene', 'id'],delimiter=' ')
genes.head()

gene
id           
16334    ins2
19241  tmsb4x
16333    ins1
67945   rpl41
11461    actb

In [4]:
# clean the data :



#load the matrix
expression_df = pd.read_hdf(folder+"/exprMatrix.h5",index_col=0)

#clean the data

expression_df.index.rename('cell_id',inplace=1)
expression_df.shape

gene_names=[genes['gene'].ix[id] for id in expression_df.columns.values]
expression_df.columns=gene_names

expression_df.head()

expression_df=expression_df.loc[:, (expression_df != expression_df.iloc[0]).any()]  # remove constant columns
expression_df.shape

expression_df=expression_df[(expression_df.T != 0).any()] # remove rows of zeros
expression_df.shape


gene_count=expression_df.astype(bool).sum(axis=0)
cells=expression_df.count()
expression_df=expression_df[gene_count[gene_count>cells/10].index]
expression_df.shape


expression_df.head()



expression_df=(100*expression_df.transpose() / expression_df.sum(1)).round(2).transpose()


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  del sys.path[0]


In [5]:
expression_df.shape

(4124, 13042)

In [7]:
# this function takes x and y and returns the image, number of bins determine the resolution. We will use this function later 
# in our construction for the image

def myplot(x, y, s, bins=150):
    heatmap, xedges, yedges = np.histogram2d(x, y, bins=bins)
    heatmap = gaussian_filter(heatmap, sigma=s)
    return heatmap.T 

In [8]:
# this function to read the file "pairs" and the the label assocaited with these pairs...example of what this function does 
# is in the next cell

def load_point_cloud_from_hd(path):
     entiregraph=[]
     y=[]
     with open(path) as f:
         for line in f:
             numbers_str = line.split()
             numbers_float = [str(x) for x in numbers_str]  #map(float,numbers_str) works too
             val=float(numbers_float[-1])
             if val!=2:          
                 y.append(val)
                 entiregraph.append(numbers_float[:-1])
                 
     return np.array(entiregraph),y


In [9]:
pairs,y_=load_point_cloud_from_hd("C:/CS230/dendritic_gene_pairs_200.txt")


In [12]:
# print the pair and the label assocatied with it
print(pairs[0])
print(y_[0])

print(pairs[1])
print(y_[1])

['stat3' 'tonsl']
1.0
['stat3' 'exd1']
0.0


In [28]:
# we can use the pairs with the expression_df as follows:
# lets take the first pair :

pair0=pairs[0]
gene_a=pair0[0]
gene_b=pair0[1]

print(gene_a)
print(gene_b)

stat3
tonsl


In [30]:
# we can input these genes to the table expression_df
expression_df[[gene_b,gene_b]]

# be careful here not all pairs in the file "pairs" are in expression_df so one has to check first if the pair exists in 
# expression_df

tonsl  tonsl
cell_id                                     
GSE48968_GSM1189043_SRR935907     0.0    0.0
GSE48968_GSM1189045_SRR935909     0.0    0.0
GSE48968_GSM1189047_SRR935911     0.0    0.0
GSE48968_GSM1189048_SRR935912     0.0    0.0
GSE48968_GSM1189049_SRR935913     0.0    0.0
GSE48968_GSM1189050_SRR935914     0.0    0.0
GSE48968_GSM1189051_SRR935915     0.0    0.0
GSE48968_GSM1189052_SRR935916     0.0    0.0
GSE48968_GSM1189053_SRR935917     0.0    0.0
GSE48968_GSM1189055_SRR935919     0.0    0.0
GSE48968_GSM1189056_SRR935920     0.0    0.0
GSE48968_GSM1189057_SRR935921     0.0    0.0
GSE48968_GSM1189059_SRR935923     0.0    0.0
GSE48968_GSM1189060_SRR935924     0.0    0.0
GSE48968_GSM1189062_SRR935926     0.0    0.0
GSE48968_GSM1189063_SRR935927     0.0    0.0
GSE48968_GSM1189064_SRR935928     0.0    0.0
GSE48968_GSM1189065_SRR935929     0.0    0.0
GSE48968_GSM1189066_SRR935930     0.0    0.0
GSE48968_GSM1189068_SRR935932     0.0    0.0
GSE48968_GSM1189069_SRR935933     0.0    0.0
GSE48968_GSM1189070_SRR935934     0.0    0.0
GSE48968_GSM1189073_SRR935937     0.0    0.0
GSE48968_GSM1189074_SRR935938     0.0    0.0
GSE48968_GSM1189077_SRR935941     0.0    0.0
GSE48968_GSM1189078_SRR935942     0.0    0.0
GSE48968_GSM1189080_SRR935944     0.0    0.0
GSE48968_GSM1189082_SRR935946     0.0    0.0
GSE48968_GSM1189083_SRR935947     0.0    0.0
GSE48968_GSM1189086_SRR935950     0.0    0.0
...                               ...    ...
GSE78779_GSM2076633_SRR3196056    0.0    0.0
GSE78779_GSM2076634_SRR3196057    0.0    0.0
GSE78779_GSM2076635_SRR3196058    0.0    0.0
GSE78779_GSM2076636_SRR3196059    0.0    0.0
GSE78779_GSM2076637_SRR3196060    0.0    0.0
GSE78779_GSM2076638_SRR3196061    0.0    0.0
GSE78779_GSM2076639_SRR3196062    0.0    0.0
GSE78779_GSM2076640_SRR3196063    0.0    0.0
GSE78779_GSM2076641_SRR3196064    0.0    0.0
GSE78779_GSM2076642_SRR3196065    0.0    0.0
GSE78779_GSM2076643_SRR3196066    0.0    0.0
GSE78779_GSM2076644_SRR3196067    0.0    0.0
GSE78779_GSM2076645_SRR3196068    0.0    0.0
GSE78779_GSM2076646_SRR3196069    0.0    0.0
GSE78779_GSM2076647_SRR3196070    0.0    0.0
GSE78779_GSM2076648_SRR3196071    0.0    0.0
GSE78779_GSM2076649_SRR3196072    0.0    0.0
GSE78779_GSM2076650_SRR3196073    0.0    0.0
GSE78779_GSM2076651_SRR3196074    0.0    0.0
GSE78779_GSM2076652_SRR3196075    0.0    0.0
GSE78779_GSM2076653_SRR3196076    0.0    0.0
GSE78779_GSM2076654_SRR3196077    0.0    0.0
GSE78779_GSM2076655_SRR3196078    0.0    0.0
GSE78779_GSM2076656_SRR3196079    0.0    0.0
GSE78779_GSM2076657_SRR3196080    0.0    0.0
GSE78779_GSM2076658_SRR3196081    0.0    0.0
GSE78779_GSM2076659_SRR3196082    0.0    0.0
GSE78779_GSM2076660_SRR3196083    0.0    0.0
GSE78779_GSM2076661_SRR3196084    0.0    0.0
GSE78779_GSM2076662_SRR3196085    0.0    0.0

[4124 rows x 2 columns]

In [35]:
d=expression_df[[gene_a,gene_b]]
d=d[d[gene_a]*d[gene_b]>0.5]
print(d)


# here is it empty 

Empty DataFrame
Columns: [stat3, tonsl]
Index: []


In [37]:
#we can try differnt threshold :

d=expression_df[[gene_a,gene_b]]
d=d[d[gene_a]*d[gene_b]>0.0]
print(d)

# in my code I skipped the empty ones

                               stat3  tonsl
cell_id                                    
GSE48968_GSM1189344_SRR936302   0.01   0.01


In [39]:
x=np.log2(d+1)[gene_a].values
y=np.log2(d+1)[gene_b].values  

In [40]:
print(x)

[0.01435529]


In [41]:
print(y)

[0.01435529]


In [44]:
# now compute the image
img = myplot(x, y, 16,bins=150)

In [45]:
img

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [50]:
# we need to do the above for every pair in expression_df and hence the following function :

def generate_data(expression_df,pairs,y_values,s=16,threshold=0.5,size=None):
    
        
    expression_df = expression_df.loc[:,~expression_df.columns.duplicated()]
    X=[]
    y_out=[]
    for pair,k in zip(pairs,y_values):
        
        if size!=None:
            
            if len(X)>size:
                break
        
        gene_a=pair[0]  
        gene_b=pair[1]
        
        if gene_a in expression_df and gene_b in expression_df : # check if the genes are in the table before plugging them in
            d=expression_df[[gene_a,gene_b]]
            d=d[d[gene_a]*d[gene_b]>threshold] # here we use the threshold 
        
        
            x=np.log2(d+1)[gene_a].values
            y=np.log2(d+1)[gene_b].values  


            
            if len(x)!=0:
                if len(x.shape)!=1:
                    
                    continue
                else:
                    
                      
                    img = myplot(x, y, s,bins=150) # create the image
                    
                    X.append(img)
                    y_out.append(k)
                    
                    
            else:
                
                    img = myplot(x, y, s,bins=150)  # create the image
             

                    X.append(img)
                    y_out.append(k)
              

        
    
    return np.array(X),np.array(y_out)

In [51]:
# running may take a while : (I choose the size to be 1000 for speed)
X,y=generate_data(expression_df,pairs,y_,s=16,threshold=0.5,size=1000)

In [57]:
# so now you have an image X and its assoicated binary label y
print("image")
print(X[0])
print("LABEL")
print(y[0])

image
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
LABEL
1.0


In [ ]:
# you can save them to HD using the following command :

import pickle

with open('C:/CS230/X_Data_all.pkl','wb') as f:
    pickle.dump(X, f)

with open('C:/CS230/y_Data_all.pkl','wb') as f:
    pickle.dump(y, f)

In [65]:
# now define the NN model :

def define_model_1(num_classes=3,shape_input=(32, 32, 1)):


    inputs = Input(shape=shape_input)

    x=Conv2D(32, kernel_size=(3, 3),
                     activation='relu')(inputs)
    x=Conv2D(64, (3, 3), activation='relu')(x)
    x=MaxPooling2D(pool_size=(2, 2))(x)
    x=Dropout(0.25)(x)
    x=Flatten()(x)
    x=Dense(128, activation='relu')(x)
    x=Dropout(0.5)(x)
    predictions=Dense(num_classes, activation='softmax',name='final_output')(x)


    model = Model(inputs=inputs, outputs=predictions)
    print("model is defined")    
    return model

In [66]:
# define other functions needed for splitting the data, training the model,etc :

def prepare_data(X,y):        
    
    img_rows, img_cols = 150, 150
    
    # the data, split between train and test sets
    x_train, x_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42)


    x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
    x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)

    x_train = x_train.astype('float32')
    x_test = x_test.astype('float32')
    x_train /= 0.49434793151473155
    x_test /= 0.49434793151473155
    print('x_train shape:', x_train.shape)
    print(x_train.shape[0], 'train samples')
    print(x_test.shape[0], 'test samples')
    
    # convert class vectors to binary class matrices
    y_train = keras.utils.to_categorical(y_train, 2)
    y_test = keras.utils.to_categorical(y_test, 2)
    
    return x_train, y_train, x_test, y_test


def train_model(model, x_train, y_train,x_test, y_test, batch_size=128,epochs=30):


    model.compile(loss=keras.losses.categorical_crossentropy,
                  optimizer=keras.optimizers.Adadelta(),
                  metrics=['accuracy'])
    print("training the model")
    history=model.fit(x_train, y_train,
              batch_size=batch_size,
              epochs=epochs,
              verbose=1,
              validation_data=(x_test, y_test))
    print("done training the model")
    score = model.evaluate(x_test, y_test, verbose=0)
    print('Test loss:', score[0])
    print('Test accuracy:', score[1])

    
    return history

In [67]:
# split the data : 

x_train, y_train, x_test, y_test = prepare_data(X,y)




x_train shape: (800, 150, 150, 1)
800 train samples
201 test samples


In [71]:
# Define the model : 

# input is the resolution of the image--in our case it is 150 by 150

model=define_model_1(num_classes=2,shape_input=(150, 150, 1))

model is defined


In [70]:
# check the summary
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 150, 150, 1)       0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 148, 148, 32)      320       
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 146, 146, 64)      18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 73, 73, 64)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 73, 73, 64)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 341056)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               43655296  
__________

In [ ]:
# train the model :
# choose higher epochs for your training --i choose a lower number because of time
train_model(model, x_train, y_train,x_test, y_test,batch_size=128,epochs=1)


training the model
Train on 800 samples, validate on 201 samples
Epoch 1/1
